name: "A-WTF"
description: "Andres Ivanov's personal wesbite on .wtf domain."

url: "http://andres.wtf"

markdown: rdiscount
permalink: pretty

exclude: [buildspec.yml, CNAME]

plugins:
  - jekyll-minifier
