version: 0.2

phases:
  install:
    commands:
      - apt-get update && apt-get -y install nodejs
      - gem install jekyll jekyll-minifier
  build:
    commands:
      - jekyll build -d build_output
      - aws s3 cp --recursive --acl public-read build_output s3://awtf-web
  post_build:
    commands:
      - echo done

artifacts:
  type: zip
  files:
    - 'build_output/**/*'
